### ISSUE TITLE
Allow parameter for custom base source directory

### ISSUE THREAD

**Issue by rfkrocktk** [rvanlaar/djangorecipe#72]
When I use the project initialization feature, the project is initialized in the `./` directory rather than in the `src` directory. My buildout.cfg looks like this:

```
[buildout]
parts = python_section pydev_section django_section ipython_section
develop = .
eggs = projectname
versions = versions

[versions]
django = 1.5.0
ipython = 0.13.1

[pydev_section]
# for working in eclipse
recipe = collective.recipe.pydevproject
name = myproject
src = src
python_version = python 2.7
python_interpreter = Default
eggs = ${buildout:eggs}

[python_section]
recipe = zc.recipe.egg
interpreter = python
eggs = ${buildout:eggs}

[ipython_section]
recipe = zc.recipe.egg:scripts
eggs = ${buildout:eggs}
    ipython
scripts = ipython

[django_section]
recipe = djangorecipe
project = myproject
settings = development
control-script = django
eggs = ${buildout:eggs}
wsgi = true
fcgi = true
```

djangorecipe seems to create the source folder in `./` rather than in `src/`, as would be expected. I can move the project without any problems, but it's kind of annoying, as I'm writing a custom project-generation script.

I'd expect to see a folder at `src/myproject`, but instead I see `./myproject`.

**Comment by reinout** [comment]
I've removed the project generation functionality as django does it itself already.
