### ISSUE TITLE
Djangorecipe always forces the download of latest packages

### ISSUE THREAD

**Issue by anjos** [rvanlaar/djangorecipe#88]
This recipe works almost perfectly for me: It seems that the recipe does not respect the buildout setting `newest = false`  and keeps downloading all packages listed in `buildout:eggs` **and** its dependencies.

Is there anything on the recipe that forces the download of the eggs and does not respect that setting (maybe implicitly)? Looking at the code for this package or zc.recipe.egg's, I could not identify any obvious problems.

Here is my `buildout.cfg` which should work:

```ini
[buildout]
parts = django
newest = false

[django]
recipe = djangorecipe
```

OS information: OS X with the latest MacPorts Python 2.7.9 + py27-django (package installed).

Instructions to reproduce the issue:

1. Download the bootstrap: https://bootstrap.pypa.io/bootstrap-buildout.py
2. Create a `buildout.cfg` on the same directory with the contents above
3. Run `/opt/local/bin/python2.7 bootstrap-buildout.py` and then `./bin/buildout`

Result: Django is downloaded and installed. 

Expected result: Django should be re-used from the system since `newest = false`.

Could you actually confirm this behaviour with your setup?

**Comment by reinout** [comment]
I'll probably look at it early next week. (Note: feel free to ping me if I haven't done anything by wednesday :-) )

For downloading, we use buildout's standard zc.recipe.egg functionality. There was an earlier pull request (see https://github.com/rvanlaar/djangorecipe/pull/79/files), though, that fixed relative paths. That's an option from buildout that djangorecipe had to explicitly pass to zc.recipe.egg.

In the same way, we might need to explicitly pass along the 'newest=False' option. At least, that's the direction I'd be looking at.

btw, could you look which version of buildout and setuptools you're using? If 'newest=false' it could be anything :-) And they changed quite a lot in setuptools in the last months... Though I suspect it is djangorecipe I'll have to look at and not setuptools.

**Comment by anjos** [comment]
I confirmed this problem on my Debian box now.

If I list my installed eggs, I find:

zc.recipe.egg-2.0.1-py2.7.egg/
zc.buildout-2.3.1-py2.7.egg/

The annoying bit is that one of my eggs in `${buildout:eggs}` uses numpy - as a result, it downloads and re-compiles it, what takes some time at new deployments.

**Comment by reinout** [comment]
If the Debian numpy is good enough, Google for "syseggrecipe" :-)

**Comment by anjos** [comment]
I know of this one, but, why shouldn't "newest = false" work in this case?

**Comment by anjos** [comment]
Actually, since zc.buildout gave up the "isolated python" ideas from the 1.x branch, `syseggrecipe` should not be a required recipe anymore. If `newest = false` is set, then `zc.buildout` should just re-use packages existing on the "system" (i.e. the Python environment used to bootstrap), if possible (i.e., there are no other version requirements that conflict or require you to upgrade).

Or am I totally wrong here?

**Comment by reinout** [comment]
You are at least partially wrong here :-)

You're right that buildout doesn't try to provide an isolated python. But The only packages buildout knows about are the packages it manages itself (in the local `eggs/` cache folder or a global egg cache if you configured it). Buildout doesn't know about packages you installed system-wide.

So if you depend on numpy, buildout will install numpy for you.

The trick of syseggrecipe is that it **does** look for globally-installed packages. If found, it installs them as a development egg in `development-eggs/`. Where buildout finds it, so that it doesn't need to download it again.

**Question**: the django that you expect buildout to re-use, is that a django you installed globally? "`pip install django`"? Or is it a django from buildout's own egg cache?

**Comment by anjos** [comment]
I understand, though this is unexpected: the python environment is not isolated but explicitly ignores installed eggs.

The egg I'm referring to is globally installed, clearly - therefore my confusion.

I think you can safely close this problem in this case.

**Comment by reinout** [comment]
It is quite hard to reliably figure out everything that's installed globally. So many locations, so many different package name/directory name complications...

So buildout only explicitly manages what it can manage and what it explicitly knows about (=what it installed).

Anyway, good that it's clear now :-)
