### ISSUE TITLE
uwsgi configuration hints to deploy django build with djangorecipe

### ISSUE THREAD

**Issue by sandroden** [rvanlaar/djangorecipe#98]
Hi,

I've been uwsgi djangorecipe for several years now along with uwsgi. Last week I had serious problems due to the fact that import broke completely in a namespaced package due to a (probably mistaken) configuration of the same namespace being present in the system environment.

What puzzles me is that I thought to be completely isolated: I created a virtualenv and used the python interpreter in that virtualenv to generate the boostrap and subsequently bin/django.

My question is what's the uwsgi configuration you're using to deploy a djangorecipe generated project?

currently I'm using:

```
env = DJANGO_SETTINGS_MODULE=web.settings
prj_dir = /home/www/3palchi-test
wsgi-file = %(prj_dir)/bin/django.wsgi
```

but this turns out in a sys.path in uwsgi that has at the end:

```
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
```
i.e.: it sees all the system installed packages. What is the suggestion to safely deploy with uwsgi?

bin/django.wsgi lok somthing like:

#!/home/www/.virtualenvs/base2/bin/python

```
import sys
sys.path[0:0] = [
  '/home/www/.buildout/eggs/Django-1.10.6-py2.7.egg',
  '/home/www/.buildout/eggs/ipython-5.1.0-py2.7.egg',
  '/home/www/.buildout/eggs/Sphinx-1.4.6-py2.7.egg',
  ...
```

thanks in advance
sandro

**Comment by reinout** [comment]
It looks like you're mixing virtualenv/pip and buildout in some way. Perhaps you're installing uwsgi globally? It looks like it because of all those system directories. Especially something like "lib-tk" wouldn't ever be added by buildout.

I'm not using uwsgi but gunicorn (which is similar). My project's `setup.py` has a dependency on gunicorn, so buildout installs it for me. With `bin/gunicorn` I can therefore run the wsgi file just fine.

Would that help?

**Comment by sandroden** [comment]
Sorry for not being clear. Buildout is just doing things correctly in my opinion and `bin/django shell` has the path correctly set with no system paths.

The path is added by uwsgi. To see those files (added to the sys.path collected by buildout) I had to print them from within the django.wsgi file.

The way I produce it is that I create an empty virtualenv `mkvirtualenv -p /usr/bin/python2 base` (or equivalent for py3) and use the python interpreter in that virtualenv to run 'python boostrap.py'. 

uwsgi has an option to use a virtualenv, that clearly I cannot use as my virtualenv (base2) would be almost empty, so I declare the wsgi_file as shown above. It seems as if in this case the uwsgi process is not isolated from the system python env. In particular I'm using uwsgi in the emperor-vassals configuration.

**Comment by sandroden** [comment]
I solved the issue by adding the virtualenv directive. More explanation in the same [issue](https://github.com/buildout/buildout/issues/446) opened in the buildout as reported above. Thanks for the attention.
